travis:
  secure:
    BINSTAR_TOKEN: AXbmPEzI4fNqTD8qUEdAyuOteF571mRpA+VxAEHu3bhFVbsBJU9+LHzzJcfQItBld7cc3muiuT1fYC88cIjgc1hJd33vvgPK91LP2FObD1YSPzE8StfGJNkpK97c1FW1XVE7hbP1ykDGy0uhYUT/hesU1SXMUe+7dlEjRnzQtXnUrvEOQ7SFzBcleWUmZb/EpgVafJLFvL9IzkbxAOtLbYa9AjvuwLUnHQ+1f0naiBmvw2amLw+Wfijg4KI3LKXikVsuCx1lAgRDYrbg2aYyBen85wxQ25wzgcii+IAdsdW/MBHf3EF7CEkqKVA/dU8iSjiz1Ap6s7viBQUjesekJAiFlbN5ymSqvDweWh9kGL6KF1KYfCTehZcvXjVgOjtbkWqlbVWF1yZNHto8ETRWWXi4XFMyQZNNTr75iRVdn4/wafa0ilkPoM1swZqIJaZbDMXZUxp6KZmAlIOoU4sxZfzERDWcI10GsXDjmaP+h5R/EMT9Aqqx+7rkVn60+SebcjhW3l/y6lfTVK6sKrW764tsCmygH4CJpzxT959uD8ptPs4K5WPe7RDP8+mAvS0M7UbNEWPSbVT6O4ZMd+WsRdDq430dCuUNdLK35X5vBkTmQPsvu+3iqDfVEjlj2DyeaJiu9fczZf+BFGofk82hCN32CnybEARYg3dACjl5HZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
